### ISSUE TITLE
Update default logo for token and network

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#100]
Describe the task
Update logo for:
- [x] Update default logo for token (Link design: ...)
  - EVM
  - Rune
  - BRC-20  (not-yet)
- [x] Update default logo for custom network
- [x] Update default logo for NFT

Link design: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2058-69&t=7ShLNXu7joyvau7G-1 

Rule: https://www.notion.so/subwallet/Token-m-c-nh-959644b70df74356ade7ee5bf4e8296a?pvs=4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/WEBzkSWqMwiNW26

- [ ] Wrong logo for BRC-20 token
Expect : Show logo default OpenBit 
Link logo : https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2058-109&t=4zhuXOsElXM5ckQS-4


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/73d27f1d-b3fb-4613-a73f-05c0fe6cad84)

- [ ] Wrong logo for custom token ( Rune)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/354d589c-c599-41b4-bdd9-e844ec019584)



- [ ] The token logo is missing from the token detail screen
Actual : 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/b96bfdd0-c514-4490-928c-fa7acd1086e9)

Expect : 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/e8bce0f9-7e18-4e0d-a161-b39595c56f86)

- [ ] Update logo for inscription on Collectibles feature
Expect : https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2058-113&t=4zhuXOsElXM5ckQS-4
Actual : 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/8f297b24-1e30-4c07-8580-1a9a02bf1fe3)

**Comment by haiyenvu23** [comment]
=> Related to issue #143
