### ISSUE TITLE
Distinguish between token mainnet and testnet

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#101]
**Describe the task**
Distinguish between token mainnet and testnet

- [x] Token list
- [x] Network list
- [x] Select address

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/0a1b1f8e-e6e4-41e1-b84c-b10c335a21aa)

**Comment by Sokol142196** [comment]
- [ ] Update URL when click on Help button on Expand view
  - Expect: redirect to https://docs.openbit.app/

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/767bf31a-26a1-45f8-a8f2-77e6c00aae0e)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/gT6bJaYcMQrpcNz
Validation passed 

- Update URL when click button help
- Update logo bitcoin testnet


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/90ab3d08-c2de-43a0-9db6-01c1c6f02397)
