### ISSUE TITLE
Bug related to Send fund feature

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#106]
Describe the bug
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f

- [x] ~Display wrong balance~

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/bef22178-707a-4c68-addf-0bb4d3478445)

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/864ae00e-569d-4961-83be-e9237a9bfad2)

- [x] Transaction failed 

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/24f12e48-13f8-483d-9be5-0a1d8cee5839)

  - Log 
    ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/79c94ae2-fd70-4356-8756-a64f0461e4f2)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/xnxjQn58jwJdk7d
Validation passed in case
- Check logic calculate fee
- Check logic calculate Transfer max
- Check logic calculate Transfer 
- Check logic filter UTXO
- Check the information displayed on the UI


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/7dab97d4-631f-46f4-8a7a-16e78e3fd5a2)
