### ISSUE TITLE
Update new brand logo for some screen

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#108]
**Describe the task**
Update new brand logo on the screens
  - [x] Expand view 
  - [x] Setting screen
  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/50d31080-0f54-43dd-915e-741b3e1b797c)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tKmmCfy99S7mKn4

- [ ] Re-check padding for logo


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/259a9efa-d7f8-480b-850b-0ec8de433d2e)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/FgFzw4iRx2KR7td
Validation passed 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/41a5ba9c-94fd-44f3-9444-a35c7131fe5b)
