### ISSUE TITLE
Add "Beta version" for main screens

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#122]
**Describe the task**
Add "Beta version" for main screens
- Design: follow-up by design

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/aZC6KcqEcjzHjDM

- [ ] Some screens do not have Beta version text yet
Link design : https://www.figma.com/design/eCB1RUiaiEBmR0dDMFlUyO/02.OpenBit-Apps?node-id=15870-158072&t=Qgf6Y1NruwwV8oTY-0

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/af69d23e-8908-47c8-9822-5668cf5b9a9b)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/0563f3f6-b700-4a34-9d39-8f5e3af27b48)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/69e65d33-9726-4b08-ba3d-9170492b5979)
