### ISSUE TITLE
Update fallback fee for transfer token feature

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#136]
**Describe the task**
Update fallback fee for transfer token feature

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/EjNHsP39kBKKK3R
Validation passed in case : 
- There is a lot of utxo but not enough amount transfer (input > 0) -> keep logic
- No utxo (input = 0) -> increase input amount by 1 when estimating fee


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/6379b297-91c1-4322-bc74-56dc925445af)
