### ISSUE TITLE
Reorder ordinal for API request to force run some feature

### ISSUE THREAD

**Issue by S2kael** [openbitdev/OpenBit-Wallet#139]
In some cases, the wallet has too many accounts and many assets.
In all account mode, sending funds will be delayed to fetch data.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/iW7xErYDCLTYCm2
Validation passed in case : 
- In case there are many accounts in the wallet, getting balance is improved faster


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/15a9366f-c155-4d6d-b917-aa2639aa36ef)
