### ISSUE TITLE
Re-calculate btc balance

### ISSUE THREAD

**Issue by S2kael** [openbitdev/OpenBit-Wallet#141]

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/ijN2TfCnpDz6zp9
Validation passed in case : 
- When transaction unconfirmed, balance show in wallet like on mempool ( Sender and Recipient)
- Can get output in transaction unconfirmed to use for input in transaction next


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/5d15f1ca-7ada-4e39-806c-8b3d8a67888b)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/2ad8cfea-a059-425d-a852-91fa3886a0a6)
