### ISSUE TITLE
Migrate API Proxy (Round 2)

### ISSUE THREAD

**Issue by bluezdot** [openbitdev/OpenBit-Wallet#169]
- [x] Fix error display Transaction id, duplicate transaction history
- [x] Fix Transaction status display in Transaction history

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/KQWwdTCGfGm2qwF
Validation passed in case : 
- Fix error display Transaction id, duplicate transaction history
- Fix Transaction status display in Transaction history


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/37f8dd2b-b328-4c21-8c7b-53415219d7fe)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/ba1ed7c1-4adb-4b54-b253-40e92b55aa7c)
