### ISSUE TITLE
Update price for Rune and Ordinal popular

### ISSUE THREAD

**Issue by haiyenvu23** [openbitdev/OpenBit-Wallet#181]
**Describe the task**
Update price for Rune and Ordinal popular

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/50d72fab-d51e-4cc3-93c9-474cfcc0067d)

**Comment by haiyenvu23** [comment]
- [ ] Update price for token BTC on BEVM network


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/93e96aa4-68bb-42c1-9c6f-defb95a743bd)

**Comment by bluezdot** [comment]
Rune price
- [ ] RUNES•X•BITCOIN: https://www.coingecko.com/en/coins/runes-x-bitcoin
- [ ] DOG•GO•TO•THE•MOON: https://www.coingecko.com/en/coins/dog-go-to-the-moon-runes-2
- [ ] RSIC•GENESIS•RUNE: https://www.coingecko.com/en/coins/rsic-genesis-rune
- [ ] UNCOMMON•GOODS: https://www.coingecko.com/en/coins/uncommon-goods
- [ ] EPIC•EPIC•EPIC•EPIC: https://www.coingecko.com/en/coins/epic-epic-epic-epic

**Comment by bluezdot** [comment]
BRC20 Price:
- [ ] trac: https://www.coingecko.com/en/coins/trac-ordinals
- [ ] wzrd: https://www.coingecko.com/en/coins/bitcoin-wizards
- [ ] ordi: https://www.coingecko.com/en/coins/ordi
- [ ] MUBI: https://www.coingecko.com/en/coins/multibit
- [ ] PUPS: https://www.coingecko.com/en/coins/pups-ordinals
