### ISSUE TITLE
Handle show inscriptions by batch

### ISSUE THREAD

**Issue by bluezdot** [openbitdev/OpenBit-Wallet#182]
- [x] Load inscription by batch (25)
- [x] Display total inscription at begining
- [x] Reload to update inscription balance

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/jts9GoHXWX2tFEy

- [ ] When import account, don't show inscription, have to press reload for the inscription to appear


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/1fa33a2a-c3f0-46cf-9f81-84a48f731c2c)

- [ ] In all account mode, total is displayed incorrectly


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/79361679-bbb6-4c9c-89b5-273a10745b40)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/T3tRf2LAyHtzsaF

- [ ] When import account, don't show inscription, have to press reload for the inscription to appear
Account test : bc1pp2ae89ql6e2ye2aafsvswff72hscxhl4leq8z3sx5ajryh8h49rqcrkphc


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/05bdcf12-d59e-463e-9111-09dd795d7360)

**Comment by haiyenvu23** [comment]
Version test : 
-  http://14.224.129.242:8900/s/jom4JqJ2w3acrNG
- (Firefox): http://14.224.129.242:8900/s/qj8XmS6w4SYM4wx
Validation passed in case : 
- Update version 
- Show list inscription on specific account mode
- Show total inscription on all account mode


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/4ef586ad-f406-4e11-8d26-89638b5397bd)
