### ISSUE TITLE
Update chainlist

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#183]
**Describe the task**
Update multi-chain asset for some tokens
- BTC:
- [x] bevm-NATIVE-BTC
- [x] merlinEvm-NATIVE-BTC
- BTC testnet:
- [x] bitlayerTest-NATIVE-BTC
- [x] botanixEvmTest-NATIVE-BTC
- [x] bitcoinTestnet-NATIVE-BTC
- Wrapped BTC:
- [x] bevm-ERC20-WBTC-0xB5136FEba197f5fF4B765E5b50c74db717796dcD
- USDT:
- [x] bobMainnet-LOCAL-USDT-0x05D032ac25d322df992303dCa074EE7392C117b9

Update price & logo:
- [x] bevm-ERC20-stBTC-0x26bda683F874e7AE3e3A5d3fad44Bcb82a7c107C: bido-staked-bitcoin
- [x] bevm-ERC20-wstBTC-0x2967E7Bb9DaA5711Ac332cAF874BD47ef99B3820: wrapped-stbtc

**Comment by haiyenvu23** [comment]
- [ ] Add support BounceBit testnet network

**Comment by bluezdot** [comment]
- [ ] Update all logo BTC Testnet

**Comment by bluezdot** [comment]
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/243
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/241

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/2pWiXakZJS5HDcd

- [ ] Don't show price for : 
- bevm-ERC20-stBTC-0x26bda683F874e7AE3e3A5d3fad44Bcb82a7c107C: bido-staked-bitcoin
- bevm-ERC20-wstBTC-0x2967E7Bb9DaA5711Ac332cAF874BD47ef99B3820: wrapped-stbtc


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/06633258-c09d-4251-a8aa-4ee373e11a67

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/f3bb8ebc-c1ed-4199-9819-c7a6a3c85692)

**Comment by haiyenvu23** [comment]
Version test : 
Validation passed in case : 
- Update version 
- Update multi-chain asset for some tokens

> - BTC : 
> -  bevm-NATIVE-BTC
> - merlinEvm-NATIVE-BTC


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/4d4b703a-019d-40ec-ae63-6d1440b3c1a9)

> - BTC testnet:
> - bitlayerTest-NATIVE-BTC
> - botanixEvmTest-NATIVE-BTC
> - bitcoinTestnet-NATIVE-BTC



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/9d3d4109-8fff-49e3-b1df-7dd68dcfd892)


> - Wrapped BTC:
> - bevm-ERC20-WBTC-0xB5136FEba197f5fF4B765E5b50c74db717796dcD


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/45cbebf1-f720-46e4-9283-28bf430e921d)


> - USDT:
> - bobMainnet-LOCAL-USDT-0x05D032ac25d322df992303dCa074EE7392C117b9



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/f729e8a9-232a-47e2-bc67-6677afb9f74b)


- Update price & logo:

> -bevm-ERC20-stBTC-0x26bda683F874e7AE3e3A5d3fad44Bcb82a7c107C: bido-staked-bitcoin

> - bevm-ERC20-wstBTC-0x2967E7Bb9DaA5711Ac332cAF874BD47ef99B3820: wrapped-stbtc



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/172c2219-d9d4-40bb-ab5d-73fb69a48b0c)

--------
 - Add support BounceBit testnet network


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/9d46373c-8dcc-4821-a605-3046f47a0c48)
