### ISSUE TITLE
Fix API return type

### ISSUE THREAD

**Issue by bluezdot** [openbitdev/OpenBit-Wallet#187]
Fix some data types:
1. API rune-metadata:
- [x] burned: number -> string
- [x] mints: number -> string
- [x] premine: number -> string
- [x] timestamp: number -> string
- [x] terms.cap

![image](https://github.com/openbitdev/OpenBit-Wallet/assets/72647326/28b02036-3829-4338-a55e-7a97955b1263)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/GbZ4ZJmAbZFbrQ4
Validation passed 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/5986bc39-06d7-4144-835a-11fb74e88123)
