### ISSUE TITLE
Optimize fee rate level 

### ISSUE THREAD

**Issue by bluezdot** [openbitdev/OpenBit-Wallet#189]
- [x] Optimize amount for fee rate level. Use the new recommended fee and time-confirmed estimate from Mempool:
- Fast: 10 minutes
- Average: 30 minutes
- Low: 1 hour

![image](https://github.com/openbitdev/OpenBit-Wallet/assets/72647326/1ace26f6-a069-4523-86fd-65fc9db6d4b0)

**Comment by bluezdot** [comment]
- [ ] Update bitcoin balance.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/zi7EQE6d7sBNBPi
Validation passed 
- Optimize amount for fee rate level. Use the new recommended fee and time-confirmed estimate from Mempool:
- Mainnet 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/9ef852cc-0516-4576-81d0-19877ebcbcf6)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/b6a6ef9a-011e-4fda-80cb-9f4930dbb632)


- Testnet 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/de68a7ac-f96d-46d7-93c9-69664762ddad)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/53e144eb-623e-4e39-831c-4fc319d1a1f5)
