### ISSUE TITLE
Error can re-import brc20 token even though the token is already in the wallet

### ISSUE THREAD

**Issue by haiyenvu23** [openbitdev/OpenBit-Wallet#194]
**Describe the bug**

- [x] Error can re-import brc20 token even though the token is already in the wallet

Actual : 

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/aafb9cb8-373e-47f2-8e8a-be9aef8f4eaa)

Expect : Validate with token in wallet

**Comment by bluezdot** [comment]
- [ ] BRC20: Check ticker has 4 or 5 bytes length to start validating BRC20 info
- [ ] Rune: Check Rune ID includes `:` to start validating Rune info

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/doFcoEbDJZWmysR
Validation passed in case : 

- When re-import token
![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/ea0d8685-db61-48d2-b24e-e477a052a25c)

- When import brc20 with 3 bytes


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/59b74fd4-8879-43d4-bd3e-d7e497207e69)
