### ISSUE TITLE
Add "Beta" for OpenBit version

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#199]
**Describe the task**
Add "Beta" for OpenBit version

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/doN4dWiXkmBogC9

- [ ] Change "OpenBit v 1.1.45-beta" -> " OpenBit v 1.1.45 (Beta) " 
![image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/1082bb13-ab0d-41f4-b1ff-59a52bb5b324)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/LXr3WspRraWFs7T
Validation passed


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/f9e37827-0514-42e7-89fc-940ce564da5e)
