### ISSUE TITLE
Add support Ordinal with video format

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#202]
**Describe the task**
Add support Ordinal with video format

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/iMz4E8FrNdkZr4S

- [ ] When import account, don't show inscription, have to press reload for the inscription to appear


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/a6daf7a3-beee-4c2e-a2d7-f0bbc7b44bc7)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/pWXEL5ezXNxJZHK

- [ ] UI bug


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/ce6962a5-58b6-4e71-b5cf-faa59eb601c2)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/YdqtbyraaymdRr7
- [ ] Update logo default Ordinal with audio content type

![Image](https://github.com/orgs/openbitdev/projects/1/assets/155931563/53b5cc19-6d3e-4fdb-9026-45f1096c44d7)

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/JNmrBGkrWjJnwRy
- (Firefox): http://14.224.129.242:8900/s/jqkKoaP2jFBRdW4

Validation passed in case : 
- Install/Update version



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/a0f06def-4f1b-45d8-a149-d6fa6039907e)
