### ISSUE TITLE
Add support for ORDINALS•RUNES token

### ISSUE THREAD

**Issue by bluezdot** [openbitdev/OpenBit-Wallet#212]
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/247

**Comment by bluezdot** [comment]
holders: https://scan-mainnet.bevm.io/token/0x041bbB9c16fDBa8C805565D0bB34931e37895EC9?tab=holders

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/JqsA3sen4das2PN
- (Firefox): http://14.224.129.242:8900/s/s9ittZ4iAnki4BS

Validation passed in case : 

- Install/Update version 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/83fc5acd-2f09-4db7-b309-041262ded809)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/8ae5f2de-439f-4b57-afef-c637797a5c67)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/f48c00e4-30d3-482d-909b-74882c233943)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/e3cc7337-8053-4bc8-942d-cf2ace2d4090)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/0ecc535c-9203-45a5-9335-f962f3ced6de)
