### ISSUE TITLE
Do not transfer token

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#22]
Describe the task

- [x] Do not transfer BIP84
  - Actual: When click on Transfer button then show error

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/f00f49ef-dd75-48ed-a23e-6f8ce7b34e93)

- [x] Do not transfer BIP44
  - Actual: When click on Approve button on Confirm transaction screen then standing on this screen, do not next step

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/94cc7794-55b7-48d8-b859-80ff23fd1eef)

=> Solution: Filter out BIP 44

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/jcs7MFK5yFdBPpR

- [ ] Can't transfer token BTC testnet


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/8d2c9a56-f118-40ff-a952-a98ddae1059f)

- [ ] Don't show transaction fee


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/2e4834a7-106d-49d2-b9db-8a0c9eaa8250)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f

- [ ] Display wrong balance 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/bef22178-707a-4c68-addf-0bb4d3478445)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/864ae00e-569d-4961-83be-e9237a9bfad2)


- [ ] Transaction failed => unknow cause


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/24f12e48-13f8-483d-9be5-0a1d8cee5839)

**Comment by Sokol142196** [comment]
Move to issue https://github.com/orgs/openbitdev/projects/1/views/6?pane=issue&itemId=64633873
