### ISSUE TITLE
Evm, miner: fix enforcing the minimum miner tip 1 wei

### ISSUE THREAD

**Issue by bluezdot** [openbitdev/OpenBit-Wallet#239]
**Is your feature request related to a problem? Please describe.**
- https://github.com/ethereum/go-ethereum/pull/28933

**Describe the solution you'd like**
Set 1 wei tips for testnet which has 0 wei tips

**Describe alternatives you've considered**
- No

**Additional context**
- No

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/DnF34dwKXStNp48
Validation passed in case : 
- Install/Update version
- Send with token testnet


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/4c41ec60-d9a9-428b-85a8-e80c072f1738)


- Send with token mainnet


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/5195c278-7ac7-44fe-b1cb-77ed7ab01922)
