### ISSUE TITLE
Fee is incorrect

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#24]
**Describe the bug**
Fee show incorrect when transfer

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/2b38001a-1cf7-470c-b741-79d9224a4d04)

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/afc6e7c1-93ae-4d20-9373-4d52c8450753)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/jcs7MFK5yFdBPpR

- [ ] Don't show transaction fee


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/21343535-08cb-4650-aaca-031fd466ea9e)

- [ ] Can't not use custom fee


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/d6642d5f-3aa7-4128-ba97-36eea59f0fbf)

**Comment by haiyenvu23** [comment]
=> Related to issue #136
