### ISSUE TITLE
Fix bug import custom EVM Rpc

### ISSUE THREAD

**Issue by bluezdot** [openbitdev/OpenBit-Wallet#244]
**Describe the bug**
- Cannot import EVM Rpc that does not has net.isNetlistening method.
![image](https://github.com/openbitdev/OpenBit-Wallet/assets/72647326/1cf0bc5b-042b-46db-8ecc-384b60166137)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/x7zRQtJtgAkMCRb

- [ ] The network is disconnected but balance is still displayed


![Image](https://github.com/user-attachments/assets/a7c52e8a-acb1-4e88-ae83-c5920d6fcdd3)



![Image](https://github.com/user-attachments/assets/1b5466ac-4b70-43db-99ad-8babb4b2a568)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/HamJEfQGeXmyk6t
Validation passed in case : 
- Install/Update version


![Image](https://github.com/user-attachments/assets/72e3730a-48ed-4a79-ae0f-0840988e41cf)


![Image](https://github.com/user-attachments/assets/f8382d4c-3bdc-4b56-8c6a-885c87c71244)



![Image](https://github.com/user-attachments/assets/881d2f3d-70d8-44c2-9228-6859d833c6a3)




![Image](https://github.com/user-attachments/assets/b44a4dd7-abef-40f6-8eb4-ca14bb652991)
