### ISSUE TITLE
Update external links

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#29]
Describe the task
Update external links
- [x] Hyperlink on Create master password
Link navigate : https://docs.openbit.app/extension-user-guide/getting-started/create-a-master-password

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/8891cd38-cd8d-49f8-83c1-61fc26a92784)

-  Communication 
  -  Website:  Coming soon
  - [x] Twitter: https://x.com/openbitapp
  - [x] Telegram: https://t.me/openbitapp
- [x] Uninstall : https://forms.office.com/pages/responsepage.aspx?id=TvDVmE92BUmZouBomlR9Hg7dzPGJ9FlOvocqIAEBi_ZUNVgzWkRXNFhGUExSTTZOMllJWFQ3UE8yRy4u
- [x] User Guide: https://docs.openbit.app/

**Comment by haiyenvu23** [comment]
- [ ] Hide logo Discord 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/bdac4fa3-c6cc-479e-9219-e61ec8290314)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/qabxaiGjTBitoPe

- [ ] Update logo github
Link design : http://14.224.129.242:8900/s/qabxaiGjTBitoPe

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/A4f4QooxnxsTeAM

- [ ] Update size logo = 24px


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/2ffc55f1-eede-4079-b800-8a44900f541a)

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/KYzkmtEAmw3e35m
Validation passed
