### ISSUE TITLE
Update style for icon

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#31]
**Describe the task**
Update style for icon

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/9002cdd5-89e9-4198-89ea-a882e1200078)

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/02cd60ac-9a0f-48e5-a97d-e083872a305b)

Design: https://www.figma.com/design/eCB1RUiaiEBmR0dDMFlUyO/02.OpenBit-Apps?node-id=16096-24513&t=QKuwOkjtuGNOWo49-4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/j3Hc4gXdw5NKftX

- [ ] Re-check UI

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/874e19ae-6f7b-4f45-b809-348e12b7e690)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/4YRfbyxDDrq5QAe
Validation passed : 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/bfc7d368-9cb5-4108-bf5c-12237c09d247)





![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/220c3303-3bac-49a6-9a12-9bb22e2de217)
