### ISSUE TITLE
Do not show Account name when Send to account in wallet

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#35]
**Describe the bug**
Do not show Account name when Send to account in wallet

- Actual: Only show address

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/ad4054bc-94a0-4815-a98b-98cdfce798b8)

- Expect: Show account name with address to separate with external account

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f
Validation passed in case : 
- Show Account name when Send to account in wallet


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/b529a3a5-bb36-40a3-a859-7486f7d28a0c)


- Show account name when the account address has been added to the address book


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/acbe9ee0-9be4-401b-8bc6-1544d6cfface)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/7e356858-78e3-467e-860e-1d3d552ebd20)


- Do not display account names with external accounts


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/456910f7-4f7f-44e1-b946-10148d649bd2)
