### ISSUE TITLE
Bug related to Transaction history

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#39]
**Describe the bug**

- [x] Do not update transaction status after transaction is confirmed in case send in wallet

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/e6cc972a-9893-42fd-8556-d48f85b2ffdc)

- [x] Still enable button "View on explorer" in case the transaction do not submit 
on chain
  - Actual: Navigate to explorer but have no data
  - Expect: Disable button

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/a744ec42-197d-4738-aa7f-32ce46655d41)

- [x] Show incorrect transaction time of the history: **Discuss more**

   ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/8ca788c9-43cc-47b9-a58e-79f3fb45f67a)

Solution: If transaction is unconfirm, move the item to Pending section. The Pending section will be at the top of the list.

- [x] UI bug on history details

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/994561db-6300-4e59-b2bc-9d00eef9b928)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f

- [ ] Handle display transaction time of the history
Actual : Dislay transaction time according to blocktime
Expect : Discuss more

![image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/96360e17-4bae-4e68-af7b-7367e900de7f)

**Comment by haiyenvu23** [comment]
- [ ] Added information "Block time/ Confirmed time" for Bitcoin transactions
- [ ] In the History List screen, transactions are grouped by "Transaction time"

**Comment by Sokol142196** [comment]
- [ ] Do not display Account Name on the transaction history
  - Expect: Display account name of the accounts in wallet
    ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/208c0c76-7d03-4f68-abf1-9d2e75cfc5e7)

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/nF3pj4JJdtk8gCx

- [ ] Do not get block time then do not show Time of block on Transaction history details
  - Check with hash: https://mempool.space/testnet/tx/6925c2199580106d19b35cb75e8dc4079d9f2cfd3c9cd4d5b10ee58a30f5c389 

  ![image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/9c1bdef7-04b9-4fd0-ac63-adbba4f40231)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/csPtTKaC5KrHG2D

- [ ] Re-check sorting transaction date
Account test : tb1qs0mc2y8gh6jrp6gs5yhclprqjtz64vvaknjz62

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/73f7133d-311b-4e9e-a123-0b8ad23037e7)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/RD8ecX4gK5fqpQt

- [ ] In case transaction confirmed , don't display Block time ( with Sender and Recipient in wallet) 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/03f02683-3c57-4f89-a96a-3ac11c24bcb9)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/eptjiTwZZxsinDw
Validation passed in case : 
- In case Send fund in wallet 
+ Transaction unconfirmed : Show Transaction time ( with Sender and Recipient )

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/336a2746-2bf6-4c95-b9d3-94f66b8cfa65)

+ Transaction confirmed : Show transaction time , block time ( with Sender and Recipient )



+ Transaction failed in wallet : Don't show transaction id, disable button View on explorer


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/cbc13c09-3166-45ba-a2b4-58327e79c099)



- In case Send fund outside the wallet
+ Transaction unconfirmed : Don't show transaction time  and block time  ( with Sender and Recipient )


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/f2182b26-1f38-4cfd-8177-becf836e3ebf)

+ Transaction confirmed : Show block time   ( with Sender and Recipient )



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/e4a9cb74-afe0-4b60-a2be-65e85d897a55)

**Comment by haiyenvu23** [comment]
- Fix : Block condition : Only after block time can it be completed
