### ISSUE TITLE
Update content in app

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#43]
**Describe the task**
Update content:
- Link content: https://www.notion.so/subwallet/Update-content-for-OpenBit-37e37eec69b14bae937b6811e1728f03?pvs=4

**Comment by Sokol142196** [comment]
Please check:
 

- [ ] Create master password, change master password 

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/50545bb1-8a3e-4c93-b434-3124d0f5b020)

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/1cf23393-ebfb-47de-a5b5-f12290345fec)

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/0859216d-0f86-4b1a-af24-27077dc9dbfe)

- [ ] Pin message 

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/b4df9e7d-07df-4c8a-a6f9-13d332b48f37)

- [ ] Export account
  
![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/a3790bf1-66a6-4cbb-a18b-75e9ac4072fc)

- [ ] Settings screen 

  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/4463ea0e-3df9-47bb-9c4b-a89f6c9f7771)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tKmmCfy99S7mKn4

- [ ] Update test for placeholder : " Search collectible name of ID "
![image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/42c3d865-b89a-46da-8a2c-a3955850df2a)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/FgFzw4iRx2KR7td
Validation passed 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/b7c63d39-dd6a-4a1c-a8d9-8a96bc36453d)
