### ISSUE TITLE
Update some screens (transfer confirmation, history...)

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#44]
**Describe the task**
Update some screens:

- [x] Transfer confirmation
- [x] History detail

Design: https://www.figma.com/design/eCB1RUiaiEBmR0dDMFlUyO/02.OpenBit-Apps?node-id=18036-26917&t=dtWBkDZcSlIhdAIy-4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/wz7BLGagR2Gn386

- [ ] Update text : => From , To


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/ea0291fd-3d72-4d12-ab00-634b7dfb164a)

- [ ] Update color account name


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/180add7b-6aec-46a2-bc63-19e22329592b)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/frogPLMLWyHsNLe

- [ ] Re-check font-weight


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/1e29268c-4fb3-43b7-befa-e3acc4d294fc)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/2c0c6352-be4e-4eb5-a685-b7e2f72bf851)



- [ ] Add text "Beta version" according to design


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/68bc180b-3861-41f4-ae4f-6a21029b878f)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/2e6b478c-2133-4a50-a1f7-62539d58ea4c)

- [ ] Re-check line color


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/fe82e937-ff81-48d3-ae01-3b42e0b148bb)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/5AGLQbkHza8Jqdp

- [ ] Update max length show account name
Link desgin : https://www.figma.com/design/eCB1RUiaiEBmR0dDMFlUyO/02.OpenBit-Apps?node-id=18278-31676&t=vsQifkJnq6XfFHbc-4

- [ ] Update padding for transaction history ( with BTC)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/g98dARit2mBog3i

- [ ]  Re-check font- weight


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/a5655a86-b8c2-4551-bf19-dd677c92a640)

- [ ] Re-check padding with long account name


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/92646472-a972-423a-bf78-78ad6769252c)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/e10673c9-8045-4e09-8914-2df45824d53a)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/kA6Y3FaHHkAH4jq

- [ ] Update content " Transaction history " -> "Send token"


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/933751eb-2d1f-421e-ac4e-42a1ebf91b10)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/gscfwrcPq7GJ9pP
Validation passed in case : 
- On transfer confirmation screen


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/eda1e802-7fdf-4e73-953d-36eee979f9e3)

- On transaction history screen


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/0553d60f-6fc3-40c3-befd-4d7ecc1d0b7b)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/c45f3587-2bb4-400c-86a8-cb4641665bf7)
