### ISSUE TITLE
Show incorrect transferable value

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#45]
**Describe the task**
Show incorrect transferable value

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/7708623b-1c53-4dbc-a32f-ca23c02fad8e)

**Comment by haiyenvu23** [comment]
Version test :http://14.224.129.242:8900/s/FgFzw4iRx2KR7td
Validation passed in case : 



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/da5c2eb2-4516-4216-bbdd-a9bebb7a4549)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/ecbfc0f4-33e9-4f8f-b36c-cf74879d9e51)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/ce80299e-d354-4823-8b48-8cf2ecfd4d3d)

- Custom token 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/7ec14ef9-9354-4bf3-afa1-7458ea69d53c)
