### ISSUE TITLE
Update account selector list

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#48]
**Describe the task**
Update style of the account selector list

**Expect:** 

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/5625fa0e-554b-4f38-89cf-a60f4230123c)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f
Validation passed 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/e71c6359-e4a6-4f04-8574-b0c5a1ea8ce4)
