### ISSUE TITLE
Update API for getAllRune and getRuneBalance

### ISSUE THREAD

**Issue by lw-cdm** [openbitdev/OpenBit-Wallet#49]
Update api fetch data and interface for runes mainnet:
- [x] API for fetching all rune collections and interface RunesCollectionInfo
- [x] API for fetching all rune balance by account and interface RunesInfoByAddress

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f
Validation passed in case : 
- Check Rune balance 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/010d6741-85c8-4329-a1a7-a09951d821e2)

- Check Rune infor


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/b2a0faea-2b7f-4369-a9ab-b5c865684e57)

- Check custom Rune


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/46373e53-c159-46dc-a75d-800a08e15475)

- Check remove custom Rune


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/4110f89f-cef3-460a-aeb7-a21fad0cbd2a)
