### ISSUE TITLE
Allow user to turn off bitcoin chains

### ISSUE THREAD

**Issue by lw-cdm** [openbitdev/OpenBit-Wallet#52]
- Do not allow to toggle bitcoin mainnet
- Allow user toggle bitcoin testnet (bitcoin testnet is disabled by default)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f
Validation passed in case : 
- Install version

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/923e139a-d21c-4cb6-92cb-fda8a3f1fe68)

- ON/OFF network


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/03dc6bca-c265-439b-b099-cd38e5931023)

- When ON/OFF network and then click Reset account/Eraser all


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/88ecc23d-db2b-4397-85d1-fcdf5f8f05af)
