### ISSUE TITLE
Recheck auto enable tokens logic

### ISSUE THREAD

**Issue by lw-cdm** [openbitdev/OpenBit-Wallet#53]
Check if auto enable tokens logic works correctly.
It is possible that if enable a network, all tokens of that network will active simultaneously.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f
Validation passed in case : 
- Check when enable token ( Mainnet, testnet, custom token)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/8cc734c0-a6b5-429e-9901-31f29240d41f)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/7b4556aa-997c-4acb-a259-3e8c3fd101df)


- Check when enable network ( mainnet, testnet, custom network)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/4f7123e4-c548-4fab-9520-46a986bd8caa)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/615625d8-1601-4489-ab6d-9fb205950943)
