### ISSUE TITLE
Fix bug UI

### ISSUE THREAD

**Issue by nampc1** [openbitdev/OpenBit-Wallet#56]
- [x] Check font-size
  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/59a167b2-3d53-4f0d-9730-efd161223ef8)

- [x] Update background on History tab
  ![image](https://github.com/openbitdev/OpenBit-Wallet/assets/44641118/5fa9b44a-0164-4f13-866f-83ed698eb6d8)
  ![image](https://github.com/openbitdev/OpenBit-Wallet/assets/44641118/1500f506-adf4-4b52-a869-16586ade639c)

**Comment by nampc1** [comment]
Postponed

- [ ] https://github.com/openbitdev/OpenBit-Wallet/issues/34
- [ ] https://github.com/openbitdev/OpenBit-Wallet/issues/32
- [ ] https://github.com/openbitdev/OpenBit-Wallet/issues/44
- [ ] https://github.com/openbitdev/OpenBit-Wallet/issues/46

**Comment by haiyenvu23** [comment]
=> Related to issue #146
