### ISSUE TITLE
Support add custom EVM tokens

### ISSUE THREAD

**Issue by nampc1** [openbitdev/OpenBit-Wallet#57]
- [x] Support adding custom ERC-20, ERC-721 on EVM networks
- [x] Fix this bug upon importing custom tokens
![image](https://github.com/openbitdev/OpenBit-Wallet/assets/44641118/084515d4-5e2b-4171-9fb8-725688c62ae5)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f
Validation passed in case : 
- Import token ERC-20


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/42dfb9a4-02be-44c3-9b6c-6bf8887349ea)

- Displays the correct balance of the account with the custom token balance


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/11d0def6-e852-49fc-82e4-632093fc315b)
- ON/OFF custom token 
- Remove custom token


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/87af52b4-7dce-495f-8ff8-b5ab3369911e)

**Comment by haiyenvu23** [comment]
Support adding custom ERC-721 on EVM networks -> Handle on issue #113
