### ISSUE TITLE
Fix token transfer flow

### ISSUE THREAD

**Issue by nampc1** [openbitdev/OpenBit-Wallet#58]
- [x] Only support transfer BTC from BIP-84 to BIP-84 accounts (https://github.com/openbitdev/OpenBit-Wallet/issues/62)
- [x] Show correct transaction history (https://github.com/openbitdev/OpenBit-Wallet/issues/39 && https://github.com/openbitdev/OpenBit-Wallet/issues/41)

**Comment by Sokol142196** [comment]
Resolved in https://github.com/openbitdev/OpenBit-Wallet/issues/62 and https://github.com/openbitdev/OpenBit-Wallet/issues/39
