### ISSUE TITLE
Calculate account balance

### ISSUE THREAD

**Issue by bluezdot** [openbitdev/OpenBit-Wallet#60]
**Is your feature request related to a problem? Please describe.**
Update account balance (BTC). 
available UTXOs = all UTXOs - pending UTXOs - inscription UTXOs - runes UTXOs

**Describe the solution you'd like**
- [x] Filter out pending UTXOs
- [x] Filter out inscription UTXOs: hiro api
- [x] Filter out runes UTXOs: runesalpha api

**Describe alternatives you've considered**
- No

**Additional context**
- No

**Comment by haiyenvu23** [comment]
Related to issue #196
