### ISSUE TITLE
Filter accounts on transfer screen

### ISSUE THREAD

**Issue by nampc1** [openbitdev/OpenBit-Wallet#62]
- [x] Remove BIP44, BIP86 from account list

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/Sik5CRDcZyMpApx

Validation passed
- Actual: Show BIP 84 and Ethereum
  ![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/130966515/b3847ff9-2cd2-4158-9d46-d9ca9056b301)
