### ISSUE TITLE
Update Send Fund UX

### ISSUE THREAD

**Issue by lw-cdm** [openbitdev/OpenBit-Wallet#64]
- Move token selector to top
- Account selector (Send from) is based on  token selector value
- Address book in address input (Send to) must be filtered based on  token selector and Send from values

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/ds8DpRyWMt5z4gC

- [ ] Update UI for Send from field and Send to field
- [ ] Error when input EVM address on Send to field
![image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/b417500d-d6ed-47e2-b3bd-7a096d4dfa89)

- [ ] Hide Estimated fee display information when sending EVM tokens on Send funds screen
![image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/e90fa3a3-622f-413c-8437-29f462da3bc2)

- [ ] Input data is reset when changing token
**Actual** : 
![1122](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/fbdaa69a-752b-4e83-8e21-0aea5e4aa268)

**Expect** : When changing the token, the account address must also change

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/PcfQSbB87bXyNHd

- [ ] Put the icon on top


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/d6600ae6-2c83-4429-b8dd-43545634991d)

- [ ] Hide this icon 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/8fb4c640-558f-4503-85c2-f114fbf657f0)

- [ ] Change text : "Send from" -> "From" , "Send to" -> "To"


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/0331271c-142d-49e3-9ba4-c31f5a207687)

- [ ] UI 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/74dc3151-6cff-4c53-b838-d8ccd0e29b89)

- [ ] Remove this line


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/a46628fd-6367-4c23-9aaf-bfdebc8bb0ba)

- [ ] Account address is reset when changing token


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/eb149072-f48c-41e3-ac72-c57e1a7bff2a)
