### ISSUE TITLE
Bug: Infinite loading when opening extension

### ISSUE THREAD

**Issue by lw-cdm** [openbitdev/OpenBit-Wallet#67]
![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/92499846/8070786e-df38-4187-85e8-2fb77d9633af)

Traces:
- UI has to wait background (serviceworker) init ready
- Table asset in indexDB has about ~ 64000 records, after caching Rune data
- Bottleneck happens with method initChains in chain-service/index.ts

**Comment by Sokol142196** [comment]
Solution: Add top Runes and BRC-20 to decrease records
