### ISSUE TITLE
Support bitcoin layer 2

### ISSUE THREAD

**Issue by lw-cdm** [openbitdev/OpenBit-Wallet#68]
- [x] Bitlayer (Mainnet & Testnet): 
- Docs: https://docs.bitlayer.org/docs/Build/QuickStart/
- Explorer: https://www.btrscan.com/
- Explorer test: https://testnet-scan.bitlayer.org
- [x] BEVM (Mainnet & Testnet): 
- Docs: https://documents.bevm.io/
- Explorer: https://scan-mainnet.bevm.io/
- Explorer test: https://scan-testnet.bevm.io
- [x] B2 Network (Mainnet): https://docs.bsquared.network/
- Explorer: https://explorer.bsquared.network/
- [x] BOB (Mainnet): https://www.gobob.xyz/#Start-Builiding
- Explorer: https://explorer.gobob.xyz/

**Comment by bluezdot** [comment]
- [ ] Merlin:
- [ ] Botanix:

**Comment by haiyenvu23** [comment]
Can't test with EVM token yet because unable to get address (shows empty Select Token screen) => Handle to issue #102

**Comment by haiyenvu23** [comment]
Version test : 
Validation passed 
- Bitlayer (Mainnet & Testnet)
Link explorer ( Tesnet) : https://testnet-scan.bitlayer.org/tx/0xee5deafb76cee8bb28f4574d0c288dd8d33873e97c186de25028045ca11a3d82

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/dd93e678-1f68-41d2-b943-c9f45c327185)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/6fb73b81-3953-4485-b68a-7d8f463ee2c8)

- BEVM (Mainnet & Testnet):
Link explorer(Tesnet) : https://scan-testnet.bevm.io/tx/0x94549f9b39873140e9eab1b2b001ea6b14a4359ead02fa43357119ee0853b111

![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/22a6d2cb-fc31-48c8-be47-02aa0b4d18c6)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/82bf8d1a-071c-4246-8ee1-1273e72b1b5c)

- B2 Network (Mainnet)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/ec73dfb2-1906-48f4-87d6-4b457bbe103d)


- BOB (Mainnet)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/5943e7bc-5bcc-4364-ba5e-bbcc55658adb)

-  Merlin (Mainnet):


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/a37c8ecc-9308-4b22-8d49-80105bff119a)

- Spiderchain (Testnet)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/48770d46-bb00-4c1f-b24b-db7ca2d4297d)

- BounceBit (Mainnet & Testnet)


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/368deb69-be39-442a-b22f-8d0d635cfae4)

-> Don't see BounceBit testnet on OpenBit
