### ISSUE TITLE
Change SubWallet keyword to OpenBit

### ISSUE THREAD

**Issue by saltict** [openbitdev/OpenBit-Wallet#88]
- [x] DB name
- [x] Github Link
- [x] Keywords

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f

- [ ] Error display message Stake DOT 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/0c7b6442-9106-4d76-aaba-1386c78de169)



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/65fdbc4d-cbbc-4e4b-8a60-c5ab7dc5731b)


- [ ] Information when console log is enabled


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/35cb25ea-1d7e-4674-9c3e-d39e778bf81f)

**Comment by saltict** [comment]
@haiyenvu23 this is library name, not come from OpenBit

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f
Validation passed 
- DB name 


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/66065f43-7419-496b-90c8-c19e98aa05eb)

- Github link
- Keyword
