### ISSUE TITLE
Custom token is lost after background reload

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#94]
**Describe the bug**
Custom token is lost after background reload

**To reproduce the behavior** 
**Steps:**
1. Go to the Manage token screen
2. Perform import token successfully
3. Observe the custom token on list token
4. Reload background then Observe the custom token on list token again

**Actual:** Custom token is lost

**Comment by Sokol142196** [comment]
Follow and re-check when run path

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/Jpo4GxifQ5cELgQ

- [ ] Re-check when re-importing the previously imported brc20 token


![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/fc0de1ee-9695-475d-9b4a-c590de220c6e)

**Comment by haiyenvu23** [comment]
Version test : https://github.com/openbitdev/OpenBit-Wallet/releases/download/v1.1.48/master-build-firefox.zip
Validation passed
![1122](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/367d8718-3b0b-4e98-9b1b-00d931f5a680)
