### ISSUE TITLE
Filter some chain for display

### ISSUE THREAD

**Issue by bluezdot** [openbitdev/OpenBit-Wallet#97]
- [x] Support all L2 Bitcoin
- [x] Others: Ethereum, Polygon, Arbitrum, Base, Optimism, Avalanche

**Comment by bluezdot** [comment]
- [ ] Add BB testnet

**Comment by Sokol142196** [comment]
- [ ] @bluezdot please re-enable "Bitcoin" and "Bitcoin Testnet"

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/tkH4isbmSTJWe4f
Validation passed
